# Ezsynth v2 Project Configuration

project:
  name: "MyFirstProject"
  # --- REQUIRED PATHS ---
  content_dir: "examples/content"
  style_path: "examples/style/000.png"
  style_indices: [0] # Must be a list, even for a single frame
  output_dir: "output/MyFirstProject"
  # --- OPTIONAL PATHS ---
  mask_dir: null # Set to null or remove if not using masks
  # --- CACHING ---
  cache_dir: "cache/MyFirstProject"
  force_precomputation: false # If true, ignores existing cache and re-computes everything

  # --- RESIZING ---
  # If true, automatically resizes the style image to match the content frames' resolution.
  # This is required by Ebsynth and prevents common errors.
  force_style_size: true

precomputation:
  # Parameters for expensive, cacheable operations
  flow_engine: "RAFT" # RAFT, GMA, FlowFormer, etc.
  flow_model: "sintel" # Model name specific to the engine
  edge_method: "Classic" # Classic, PAGE, PST

pipeline:
  # The core synthesis pipeline settings
  pyramid_levels: 6 # Set to > 1 to enable pyramidal processing
  alpha: 0.75 # Content preservation. 1.0 = full style, 0.0 = full content.
  max_iter: 200 # Optimization iterations per pyramid level
  flip_aug: false # Use flip augmentation for more style variety
  content_loss: false # Use content self-similarity loss
  colorize: true # Use advanced color matching
  use_residual_transfer: false # Experimental feature for jitter reduction
  final_pass:
    enabled: false
    strength: 1.0
  use_temporal_nnf_propagation: true
  use_sparse_feature_guide: true

blending:
  # Parameters for blending forward and reverse passes.
  # Select the solver for Poisson reconstruction.
  # Options:
  # "disabled": Skips Poisson step entirely. Fastest option, but blend seam will be visible. Default
  # "lsqr": High-quality iterative solver.
  # "lsmr": Alternative iterative solver, can be slightly faster than lsqr.
  # "cg": Conjugate Gradient solver. May be faster on some systems.
  # "amg": Algebraic Multigrid solver. Very fast for large images. Requires 'pip install pyamg'.
  # "seamless": OpenCV's seamlessClone. Fast alternative, but blends in BGR space.
  poisson_solver: "disabled"
  poisson_maxiter: null # Max iterations for iterative solvers (lsqr, lsmr, cg). null means default.
  poisson_grad_weight_l: 2.5 # Gradient weight for the L (lightness) channel during Poisson blending.
  poisson_grad_weight_ab: 0.5 # Gradient weight for the a/b (color) channels.

ebsynth_params:
  # Low-level ebsynth.dll parameters
  uniformity: 3500.0
  patch_size: 7
  search_vote_iters: 12
  patch_match_iters: 6
  stop_threshold: 5 # Stop improving pixels when change is less than this value (0-255)
  # New: Skips random search for pixels with SSD error below this. 0.0 disables. Can provide a large speedup.
  search_pruning_threshold: 50.0

  # Guide weights
  edge_weight: 1.0
  image_weight: 6.0
  pos_weight: 2.0
  warp_weight: 0.5
  # --- The sparse feature tracker is a future step ---
  sparse_anchor_weight: 50.0

# --- DEBUGGING ---
# Settings for saving intermediate visualizations to help debug issues.
debug:
  # If true, saves the computed optical flow fields as color images.
  save_flow_viz: false
  # Directory where the flow visualizations will be saved.
  flow_viz_dir: "debug/flow_viz"
