# Ezsynth v2 Project Configuration for "My Awesome Project"

project:
  name: "example_project"
  # --- REQUIRED PATHS ---
  content_dir: "projects/example_project/content"
  style_path:
    - "projects/example_project/style000.jpg"
  style_indices: [0]
  output_dir: "output/example_project"
  # --- OPTIONAL PATHS ---
  mask_dir: null # Set to null as we are not using a mask for this test
  # --- CACHING ---
  cache_dir: "cache/example_project"
  force_recompute_flow: false # If true, ignores existing flow cache and re-computes.
  force_recompute_edge: false # If true, ignores existing edge cache and re-computes.

precomputation:
  flow_engine: "NeuFlow"
  flow_model: "neuflow_sintel"
  edge_method: "PAGE"

pipeline:
  pyramid_levels: 6 # Number of levels for the synthesis pyramid
  alpha: 0.75 # Content preservation. 1.0 = full style, 0.0 = full content.
  max_iter: 200
  flip_aug: false # Use flip augmentation for more style variety
  content_loss: false # Use content self-similarity loss
  colorize: false # Use advanced color matching
  final_pass:
    enabled: true
    # How strongly to apply the final pass. 1.0 is a good default.
    # Higher values will add more sharpness/style but risk re-introducing jitter.
    # Lower values will be more stable but softer.
    strength: 1.0

ebsynth_params:
  # Low-level ebsynth.dll parameters
  uniformity: 3500.0
  patch_size: 7
  search_vote_iters: 12
  patch_match_iters: 6
  stop_threshold: 5 # Stop improving pixels when change is less than this value (0-255)
  # New: Skips random search for pixels with SSD error below this. 0.0 disables. Can provide a large speedup.
  search_pruning_threshold: 50.0

  # Guide weights
  edge_weight: 1.0
  image_weight: 6.0
  pos_weight: 2.0
  warp_weight: 0.5
  sparse_anchor_weight: 50.0

debug:
  save_flow_viz: false
  flow_viz_dir: "debug/flow_viz"
