# Ezsynth v2 Project Configuration for "My Awesome Project"

project:
  name: "example_project"
  # --- REQUIRED PATHS ---
  content_dir: "projects/example_project/content"
  style_path:
    - "projects/example_project/style000.jpg"
  style_indices: [0]
  output_dir: "output/example_project"
  # --- OPTIONAL PATHS ---
  mask_dir: null # Set to null as we are not using a mask for this test
  # --- CACHING ---
  cache_dir: "cache/example_project"
  force_precomputation: false # Set to true if you want to re-calculate flow/edges

precomputation:
  flow_engine: "NeuFlow"
  flow_model: "neuflow_sintel"
  # flow_engine: "RAFT"
  # flow_model: "sintel"
  edge_method: "Classic"

pipeline:
  pyramid_levels: 6 # Number of levels for the synthesis pyramid
  alpha: 0.75 # Content preservation. 1.0 = full style, 0.0 = full content.
  max_iter: 200
  flip_aug: false # Use flip augmentation for more style variety
  content_loss: false # Use content self-similarity loss
  colorize: false # Use advanced color matching
  final_pass:
    enabled: true
    # How strongly to apply the final pass. 1.0 is a good default.
    # Higher values will add more sharpness/style but risk re-introducing jitter.
    # Lower values will be more stable but softer.
    strength: 1.0

ebsynth_params:
  # These are good starting values
  uniformity: 3500.0
  patch_size: 7
  search_vote_iters: 12
  patch_match_iters: 6
  stop_threshold: 5

  # Guide weights (these will be used by the pipeline)
  edge_weight: 1.0
  image_weight: 6.0
  pos_weight: 2.0
  warp_weight: 0.5

debug:
  save_flow_viz: false
  flow_viz_dir: "debug/flow_viz"
